import io
import uuid
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, KeepTogether, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

from frontend.parsers import parse_markdown_report, parse_interaction_cards, parse_medications

def add_footer(canvas, doc):
    canvas.saveState()
    # Footer styling
    canvas.setFont('Helvetica', 9)
    canvas.setFillColor(colors.gray)
    
    # Left text
    canvas.drawString(40, 30, "Generated by MediTrace")
    # Center text
    canvas.drawCentredString(letter[0]/2.0, 30, "Educational Use Only | Not a substitute for professional medical advice")
    # Right text
    page_num = f"Page {doc.page}"
    canvas.drawRightString(letter[0]-40, 30, page_num)
    
    canvas.restoreState()

def infer_confidence(source):
    source_lower = source.lower()
    if "openfda" in source_lower:
        return "Medium"
    if "rxnav" in source_lower or "rxnorm" in source_lower:
        return "High"
    if not source:
        return "Low"
    return "Medium"

def get_overall_recommendation(major_count, mod_count):
    if major_count > 0:
        return "Consult your healthcare provider before combining these medicines. Immediate attention may be required."
    if mod_count > 0:
        return "Monitor for side effects and consider discussing this medication combination with a healthcare professional."
    return "No major interactions detected, but always consult your healthcare provider before starting new medications."

def generate_clinical_pdf(report_data: str) -> bytes:
    sections = parse_markdown_report(report_data)
    
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=72)
    story = []
    
    styles = getSampleStyleSheet()
    
    # Define custom typography styles
    title_style = ParagraphStyle(
        'TitleStyle', fontName='Helvetica-Bold', fontSize=24, leading=28, textColor=colors.HexColor('#0f766e'), spaceAfter=8
    )
    subtitle_style = ParagraphStyle(
        'SubtitleStyle', fontName='Helvetica', fontSize=14, leading=18, textColor=colors.gray, spaceAfter=15
    )
    heading_style = ParagraphStyle(
        'HeadingStyle', fontName='Helvetica-Bold', fontSize=16, leading=20, textColor=colors.black, spaceBefore=15, spaceAfter=10
    )
    body_style = ParagraphStyle(
        'BodyStyle', fontName='Helvetica', fontSize=11, textColor=colors.black, leading=15
    )
    body_bold = ParagraphStyle(
        'BodyBold', parent=body_style, fontName='Helvetica-Bold'
    )
    bullet_style = ParagraphStyle(
        'BulletStyle', parent=body_style, leftIndent=20, bulletIndent=10, spaceAfter=2
    )
    
    def add_separator():
        story.append(Spacer(1, 8))
        story.append(HRFlowable(width="100%", thickness=1, color=colors.lightgrey, spaceBefore=4, spaceAfter=12))

    # 1. Header
    story.append(Paragraph("<b><font color='#0f766e'>+</font> MediTrace</b>", title_style))
    story.append(Paragraph("AI Medication Safety Report", subtitle_style))
    
    report_id = f"MED-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:4].upper()}"
    generated_time = datetime.now().strftime('%d %b %Y %H:%M')
    
    header_data = [
        [Paragraph("<b>Report ID:</b>", body_style), Paragraph(report_id, body_style)],
        [Paragraph("<b>Generated:</b>", body_style), Paragraph(generated_time, body_style)],
        [Paragraph("<b>Version:</b>", body_style), Paragraph("1.0", body_style)],
        [Paragraph("<b>Analysis Engine:</b>", body_style), Paragraph("MediTrace AI", body_style)],
        [Paragraph("<b>Evidence Sources:</b>", body_style), Paragraph("RxNav + OpenFDA", body_style)]
    ]
    header_table = Table(header_data, colWidths=[120, 300])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4)
    ]))
    story.append(header_table)
    
    # Colored horizontal rule for header
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width="100%", thickness=2, color=colors.HexColor('#0f766e'), spaceBefore=5, spaceAfter=20))
    
    # Gather Data
    meds = []
    if "Your medications" in sections:
        meds = parse_medications(sections["Your medications"])
        
    major_cards = []
    if "See a doctor today" in sections:
        major_cards = parse_interaction_cards(sections["See a doctor today"])
        
    mod_cards = []
    if "Watch out for" in sections:
        mod_cards = parse_interaction_cards(sections["Watch out for"])
        
    total_meds = len(meds)
    total_major = len(major_cards)
    total_mod = len(mod_cards)
    total_pairs = total_major + total_mod
    safe_pairs = 0
    if "What looks safe" in sections and "Everything looks safe" not in sections["What looks safe"]:
        safe_pairs = max(0, (total_meds * (total_meds - 1)) // 2 - total_pairs)
        
    overall_rec = get_overall_recommendation(total_major, total_mod)
    
    # 2. Executive Summary
    story.append(Paragraph("Executive Summary", heading_style))
    
    assessment_text = "High Risk" if total_major > 0 else ("Moderate Risk" if total_mod > 0 else "Low Risk")
    assessment_color = colors.HexColor('#ef4444') if total_major > 0 else (colors.HexColor('#f59e0b') if total_mod > 0 else colors.HexColor('#10b981'))
    assessment_bg = colors.HexColor('#fef2f2') if total_major > 0 else (colors.HexColor('#fffbeb') if total_mod > 0 else colors.HexColor('#f0fdf4'))

    exec_data = [
        [Paragraph("<b>Total Medications</b>", body_style), Paragraph(f"<b>{total_meds}</b>", body_style)],
        [Paragraph("<b>Interactions Checked</b>", body_style), Paragraph(f"<b>{total_pairs + safe_pairs}</b>", body_style)],
        [Paragraph("<b>Major Risks</b>", body_style), Paragraph(f"<b><font color='#ef4444'>{total_major}</font></b>", body_style)],
        [Paragraph("<b>Moderate Risks</b>", body_style), Paragraph(f"<b><font color='#f59e0b'>{total_mod}</font></b>", body_style)],
        [Paragraph("<b>Safe Pairs</b>", body_style), Paragraph(f"<b><font color='#10b981'>{safe_pairs}</font></b>", body_style)],
        [Paragraph("<b>Overall Assessment</b>", body_style), Paragraph(f"<b><font color='{assessment_color.hexval()}'>{assessment_text}</font></b>", body_style)],
        [Paragraph(f"<b>Recommendation:</b> {overall_rec}", body_style), ""]
    ]
    
    exec_table = Table(exec_data, colWidths=[200, 260])
    exec_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 1, colors.HexColor('#e2e8f0')),
        ('SPAN', (0, 6), (1, 6)),
        ('BACKGROUND', (0,0), (-1,1), colors.HexColor('#f8fafc')),
        ('BACKGROUND', (0,2), (-1,2), colors.HexColor('#fef2f2')),
        ('BACKGROUND', (0,3), (-1,3), colors.HexColor('#fffbeb')),
        ('BACKGROUND', (0,4), (-1,4), colors.HexColor('#f0fdf4')),
        ('BACKGROUND', (0,5), (-1,5), assessment_bg),
        ('BACKGROUND', (0,6), (-1,6), colors.white),
    ]))
    story.append(exec_table)
    add_separator()
    
    # 3. Patient Medications
    if meds:
        story.append(Paragraph("Patient Medications", heading_style))
        for m in meds:
            story.append(Paragraph(f"• {m}", bullet_style))
        add_separator()
        
    # 4. Interaction Details
    # 4. Interaction Details
    if major_cards or mod_cards:
        all_cards = []
        for c in major_cards:
            c['severity_level'] = 'major'
            all_cards.append(c)
        for c in mod_cards:
            c['severity_level'] = 'moderate'
            all_cards.append(c)
            
        for i, card in enumerate(all_cards):
            card_elements = []
            
            is_major = card['severity_level'] == 'major'
            title_color = colors.HexColor('#ef4444') if is_major else colors.HexColor('#f59e0b')
            bg_color = colors.HexColor('#fef2f2') if is_major else colors.HexColor('#fffbeb')
            severity_text = "Major Risk" if is_major else "Moderate Risk"
            confidence = infer_confidence(card["source"])
            
            # Card Data Table (1-column stacked layout)
            c_data = []
            
            c_data.append([Paragraph("<b>Drug Pair</b>", body_style)])
            c_data.append([Paragraph(f"<b><font color='{title_color.hexval()}'>{card['pair']}</font></b>", ParagraphStyle('CP', fontName='Helvetica-Bold', fontSize=12))])
            
            c_data.append([Paragraph("<b>Severity</b>", body_style)])
            c_data.append([Paragraph(f"<font color='{title_color.hexval()}'><b>{severity_text}</b></font>", body_style)])
            
            c_data.append([Paragraph("<b>Evidence Source</b>", body_style)])
            c_data.append([Paragraph(card["source"], body_style)])
            
            c_data.append([Paragraph("<b>Confidence Level</b>", body_style)])
            c_data.append([Paragraph(confidence, body_style)])
            
            c_data.append([Paragraph("<b>Explanation</b>", body_style)])
            c_data.append([Paragraph(card["explanation"], body_style)])
            
            if card["reactions"]:
                c_data.append([Paragraph("<b>Top Reported Adverse Events</b>", body_style)])
                reactions_list = []
                for r in card["reactions"]:
                    reactions_list.append(Paragraph(f"• {r}", bullet_style))
                c_data.append([reactions_list])
                
            c_data.append([Paragraph("<b>Recommended Action</b>", body_style)])
            c_data.append([Paragraph(card["recommendation"], body_style)])
            
            wrapper_table = Table(c_data, colWidths=[460])
            
            t_style = [
                ('BACKGROUND', (0,0), (-1,-1), bg_color),
                ('BOX', (0,0), (-1,-1), 1, title_color),
                ('VALIGN', (0,0), (-1,-1), 'TOP'),
                ('LEFTPADDING', (0,0), (-1,-1), 15),
                ('RIGHTPADDING', (0,0), (-1,-1), 15),
                ('TOPPADDING', (0,0), (-1,-1), 0),
                ('BOTTOMPADDING', (0,0), (-1,-1), 0),
                ('TOPPADDING', (0,0), (0,0), 15),
                ('BOTTOMPADDING', (0,-1), (0,-1), 15),
            ]
            
            for r in range(1, len(c_data), 2):
                if r < len(c_data) - 1:
                    t_style.append(('BOTTOMPADDING', (0, r), (0, r), 12))
                t_style.append(('TOPPADDING', (0, r), (0, r), 4))
                
            wrapper_table.setStyle(TableStyle(t_style))
            
            if i == 0:
                # Group heading and first card together
                group = [Paragraph("Interaction Details", heading_style), wrapper_table]
                story.append(KeepTogether(group))
            else:
                story.append(KeepTogether(wrapper_table))
            
            story.append(Spacer(1, 10))
            
        add_separator()
        
    # 5. Clinical Summary
    if "Why this matters" in sections:
        why_text = sections["Why this matters"]
        if why_text and why_text.strip() != "None":
            story.append(Paragraph("Clinical Summary", heading_style))
            
            summary_parts = []
            for item in why_text.split('\n'):
                if item.strip().startswith('- '):
                    summary_parts.append(item.strip()[2:])
                else:
                    summary_parts.append(item.strip())
            
            physician_summary = " ".join([p for p in summary_parts if p])
            if physician_summary:
                story.append(Paragraph(physician_summary, body_style))
            add_separator()
            
    # 6. Medical Notice
    story.append(Paragraph("Medical Disclaimer", heading_style))
    notice_elements = []
    
    notice_text = [
        "This report summarizes publicly available drug safety information from OpenFDA and RxNav.",
        "OpenFDA adverse event reports do not prove that a medication combination caused the reported event.",
        "Always consult a qualified healthcare professional before starting, stopping, or combining medications."
    ]
    for n in notice_text:
        notice_elements.append(Paragraph(f"<b>{n}</b>", body_style))
        notice_elements.append(Spacer(1, 5))
        
    notice_table = Table([[notice_elements]], colWidths=[460])
    notice_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#f1f5f9')),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor('#94a3b8')),
        ('PADDING', (0,0), (-1,-1), 15)
    ]))
    story.append(notice_table)

    doc.build(story, onFirstPage=add_footer, onLaterPages=add_footer)
    
    return buffer.getvalue()
